// <auto-generated />
namespace DIPR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatenursingprops : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatenursingprops));
        
        string IMigrationMetadata.Id
        {
            get { return "202012181928111_update-nursing-props"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
