// <auto-generated />
namespace DIPR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class userupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202101042126493_user-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
