// <auto-generated />
namespace DIPR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migrationupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202101071624255_migration-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
